#이 파일은 github에 올리는 용으로 사용하는 Sample application-oauth2.yml 파일
#실제 사용할 때는 application-oauth2.yml 파일을 작성해서 사용해야 함

spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: #github oauth2 서버의 id
                        client-secret: #github oauth2 서버의 pw